### ISSUE TITLE
Mocha Support

### ISSUE THREAD

**Issue by GregoryCollett** [speckjs/atom-speckjs#15]
Hey,

I was wondering how to get this working with mocha?

When I set mocha as my test framework in settings I receive a notification on "build" that mocha is not a supported framework. When I checked speckjs code I see that only tape and jasmine are supported.

I assume that mocha is on the roadmap, if it is not are you open to contributions?

Cheers!

**Comment by gregRV** [comment]
Hey @GregoryCollett! Thanks for asking. As you mentioned, there currently is not support for `mocha-chai` in the SpeckJS Atom plugin (only `tape` and `jasmine`, at the moment). And if you're interested we'd definitely welcome contributions! The team is a bit busy with other endeavors these days, but feel free to ping with questions or a PR and we'll do our best to get back to you in a timely manner!

**Comment by jmatsushita** [comment]
Hi there, I think while you're not supporting Mocha then your README is misleading and you should add that the support is planned.

> SpeckJS is an npm module that parses JavaScript and outputs unit-tests. SpeckJS currently supports the Tape, Jasmine, ~~and Mocha/Chai~~ testing frameworks. Along with our Atom plugin, we have plugins available for Grunt, Gulp, as well as a standalone npm package.

**Comment by GregoryCollett** [comment]
Hey @gregRV,

Sorry for the slow reply, wow.... But thank you for the response!

As @jmatsushita has mentioned, its probably worth an update to the readme!
